/*
  Build: bundle the client with esbuild, prerender the page to static HTML, and write ./index.html.

    npm run build

  Output (all committed, so any static host serves the site as-is):
    index.html             prerendered page with critical CSS inlined
    assets/main-*.js       hydration bundle
    assets/chunk-*.js      lazy chunks (the Three.js hero scene)
    assets/fonts/*.woff2   self-hosted Geist

  Edit files in src/, not index.html: it is regenerated on every build.
*/
import { build } from 'esbuild';
import { readFile, writeFile, mkdir, readdir, rm, copyFile, stat } from 'node:fs/promises';
import { createRequire } from 'node:module';
import { gzipSync } from 'node:zlib';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const r = p => path.join(root, p);
const define = { 'process.env.NODE_ENV': '"production"', __BUILD_YEAR__: JSON.stringify(String(new Date().getFullYear())) };
const shared = { bundle: true, jsx: 'automatic', define, logLevel: 'warning', absWorkingDir: root, loader: { '.js': 'jsx' } };

// 1. Client bundle, split so the Three.js scene loads as its own chunk
await mkdir(r('assets/fonts'), { recursive: true });
for (const f of await readdir(r('assets'))) if (f.endsWith('.js')) await rm(r(`assets/${f}`));
const client = await build({
  ...shared,
  entryPoints: { main: 'src/entry-client.jsx' },
  outdir: 'assets', format: 'esm', splitting: true, minify: true, target: ['es2020', 'safari15'],
  entryNames: '[name]-[hash]', chunkNames: 'chunk-[hash]', legalComments: 'none', metafile: true,
});

// 2. Server bundle (CommonJS so bundled CJS deps can require Node built-ins), then render
const ssrFile = r('node_modules/.cache/portfolio-ssr/entry-server.cjs');
await build({ ...shared, entryPoints: ['src/entry-server.jsx'], outfile: ssrFile, platform: 'node', format: 'cjs', target: 'node20' });
const require = createRequire(import.meta.url);
delete require.cache[ssrFile];
const { html, styles } = require(ssrFile).render();

// 3. Inject into the template
const outputs = Object.entries(client.metafile.outputs);
const [entryFile, entryMeta] = outputs.find(([, o]) => o.entryPoint === 'src/entry-client.jsx');
const preloads = entryMeta.imports.filter(i => i.kind === 'import-statement').map(i => `<link rel="modulepreload" href="${i.path}" />`).join('\n  ');
const page = (await readFile(r('src/index.html'), 'utf8'))
  .replace('<!DOCTYPE html>', '<!DOCTYPE html>\n<!-- Generated by `npm run build` from src/. Edit src/, not this file. -->')
  .replace('<!--ssr-styles-->', styles)
  .replace('<!--preload-->', preloads)
  .replace('<!--ssr-html-->', html)
  .replace('<!--entry-->', `<script type="module" src="${entryFile}"></script>`);
await writeFile(r('index.html'), page);

// 4. Self-hosted fonts
for (const [from, to] of [['geist-sans/Geist-Variable.woff2', 'Geist-Variable.woff2'], ['geist-mono/GeistMono-Variable.woff2', 'GeistMono-Variable.woff2']]) {
  await copyFile(r(`node_modules/geist/dist/fonts/${from}`), r(`assets/fonts/${to}`));
}

// 5. Size report
const kb = n => `${(n / 1024).toFixed(1)} KB`;
const report = async f => { const buf = await readFile(r(f)); return `${f.padEnd(34)} ${kb(buf.length).padStart(9)}  gzip ${kb(gzipSync(buf).length).padStart(8)}`; };
console.log(await report('index.html'));
for (const [f] of outputs) console.log(await report(f));
console.log(`\nBuilt ${new Date().toLocaleTimeString()}. Entry: ${entryFile} (${(await stat(r(entryFile))).size} bytes)`);
